version: '3.8'

services:
  api:
    build: ./api
    ports:
      - 3001:3001
    volumes:
      - ./api:/usr/src/app
    environment:
      - NODE_ENV=development
      - PORT=3001
    depends_on:
      - mongodb  # Changez "mongo" en "mongodb" pour correspondre au nom du service MongoDB
      
  app:
    build: ./app
    container_name: react_app
    ports:
      - 3000:3000
    stdin_open: true
    tty: true

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
