version: '3.8'

services:
  app:
    build: ./app
    container_name: react_app
    ports:
      - 3000:3000
    stdin_open: true
    tty: true

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
